### ISSUE TITLE
too many GET request when searching by name

### ISSUE THREAD

**Issue by etshy** [piyushsinha24/flutter_bloc_example#1]
I forked your project to do some test on my own to learn BLoC Pattern and Flutter.
Your Medium article is awesome, it lacks a bit information on some files for Flutter newbies but it's really good.

I noticed a "problem" with the search bar though.
As the event is an "onChange" it does a GET request every time you tap a letter.
Do you know a way to limit the requests that are made ?

I remember doing a thing like that in AngularJS years ago, by settings some kind of small "waiting time", to check if the user is still typing.
I don't know if it's a good way to do that, but do you have an idea how to do that (on the onChange event, on a State or whatever) ?

**Comment by piyushsinha24** [comment]
Hey there, thank you for reaching out. I have implemented the **debounce search** to solve your issue and pushed the code. Please have a look and let me know if your issue is solved. I will be closing this issue after your feedback.

**Comment by etshy** [comment]
Hi. thanks for quick reaction.

First I got the error : "Error: 'Observable' isn't a type." when running the build.
Then, for some reason I don't see the "Hitting service" print you did in the `mapEventToState` method.

To test I added a `debugPrint('http get');` just before the `http.get()` in the `fetchPlayersByName` method in `player_api_provider` file. And I still see that debug each time I type a letter in the searchbox. I don't know yet how `transformEvents` work but it doesn't seem to be working.

**Comment by piyushsinha24** [comment]
`@override Stream<PlayerListingState> transformEvents(Stream<PlayerListingEvent> events, Stream<PlayerListingState> Function(PlayerListingEvent event) next) {
    // TODO: implement transformEvents
    return super.transformEvents(
      (events as Observable<PlayerListingEvent>).debounce(
        (_) => TimerStream(true, const Duration(seconds: 3)))
      ,next,
    );
  }`

**Debounce search** is the solution for this but we need to adjust the duration accordingly. Earlier I set it to **250ms** which wasn't reasonable(_typing won't finish so quick :p_) so I tried with **3 seconds** and works like charm. It hits the service once after completing the typing and once while clearing the text field. I suggest you to **fresh clone the repo** to get rid of errors.

**Comment by etshy** [comment]
I upgraded all flutter and packages versions and run a command to update code
see : https://pub.dev/packages/rxdart#upgrading-from-rxdart-022x-to-023x

Now I have this `transformEvents` (I searched for a way to debounce and found an example with `debounceTime().switchMap()` I don't know exactly what it does for now, though)
```
@override
  Stream<PlayerListingState> transformEvents(
      Stream<PlayerListingEvent> events,
      Stream<PlayerListingState> Function(PlayerListingEvent event) next,
      ) {
    return events
        .debounceTime(
      Duration(milliseconds: 300),
    )
        .switchMap(next);
  }
```
And it works like a charm, without have to settings Duration to "high value".
Maybe I upgraded packages and that got me the previous errors.



I tried again with your code, but with updated rxdart code (without Observable Class)
```
@override
  Stream<PlayerListingState> transformEvents(Stream<PlayerListingEvent> events,
      Stream<PlayerListingState> Function(PlayerListingEvent event) next) {
    // TODO: implement transformEvents
    return super.transformEvents(
      events.debounce((_) => TimerStream(true, const Duration(milliseconds: 300))),
      next,
    );
  }
```
And it works too.

Seems like the package upgrade break the code...

Thanks for everything though, it helped me a bit to understand more about flutter and things.

Edit : btw `debounceTime()` is a shortcut for the `debounce()` you call.
The code behind it is the follow : 
```
Stream<T> debounceTime(Duration duration) => transform(
      DebounceStreamTransformer<T>((_) => TimerStream<bool>(true, duration)));
}
```

So it's "faster" to do this : 
```
@override
  Stream<PlayerListingState> transformEvents(Stream<PlayerListingEvent> events,
      Stream<PlayerListingState> Function(PlayerListingEvent event) next) {
    // TODO: implement transformEvents
    return super.transformEvents(
      events.debounceTime(Duration(milliseconds: 300)),
      next,
    );
  }
```

**Comment by piyushsinha24** [comment]
Good job mate. We both learned something new today. 👍
